// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/fingo-martpedia/fingo-wallet/helpers"
	"github.com/fingo-martpedia/fingo-wallet/internal/controller"
	"github.com/fingo-martpedia/fingo-wallet/internal/interfaces"
	"github.com/fingo-martpedia/fingo-wallet/internal/repository"
	"github.com/fingo-martpedia/fingo-wallet/internal/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitDependency() Dependency {
	db := provideDB()
	walletRepository := repository.NewWalletRepository(db)
	walletService := services.NewWalletService(walletRepository)
	walletController := controller.NewWalletController(walletService)
	dependency := Dependency{
		WalletController: walletController,
	}
	return dependency
}

// injector.go:

type Dependency struct {
	WalletController interfaces.IWalletController
}

func provideDB() *gorm.DB {
	return helpers.DB
}
